baseurl      = "/"
title        = "Ph.piment's Outputs"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Oct 16, 2021"
  dateformShort   = "Oct 16"
  dateformNum     = "2021-10-16"
  dateformNumTime = "2021-10-16 15:04"

  # Subtitle for home
  homeSubtitle = "Can you do it? I can do it."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new outputs"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Ph.piment's Outputs"
    subtitle = "Can you do it? I can do it."
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Ph.piment's Outputs"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
#  [[menu.main]]
#    identifier = "blog"
#    name       = "Blog"
#    url        = "/posts"

